---
title: "w241: Experiments and Causality"
subtitle: "Incomplete Control Over Treatment Delivery"
author: "David Reiley, David Broockman, D. Alex Hughes"
institute: "UC Berkeley, School of Information"
date: "Updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, echo=FALSE, message=FALSE, include=FALSE}
library(latex2exp)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(data.table)

berkeley_blue   <- '#003262'
california_gold <- '#FDB515'

options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = TRUE, dpi = 300, fig.height = 3)


theme_set(theme_minimal())
```

class: inverse, center, middle 

#Introduction to Noncompliance

---
#Introduction

## Noncompliance in randomized experiments

- Sometimes units assigned to treatment do not actually receive treatment 
- This week, we will learn how to deal with noncompliance
  - How to analyze data correctly without inducing bias
  - How to design experiments to improve precision in the presence of noncompliance
- Leading example: Advertising experiments from earlier in the course
  - Randomly assign a person to be targeted with advertising
  - But, they don't browse to the site and so *choose* to receive zero ads
  - Or, some other advertiser non-randomly targets the person so our ad campaign cannot reach them. 

---
# Reading

## *Gerber and Green*: Chapter 5, Introduction

- This is about 4 pages of reading. 

---

class: inverse, center, middle

# Example: Get Out To Vote

---

# Introduction to Chapter 5

## Get out the vote (GOTV) example

- Treatment assigned at random
  - Canvasser knock on the doors of 1,000 treatment houses
  - Canvassers skip knocking on the doors of 1,000 control houses
  
## In the treatment Group
  - 250 subjects answer the door
  - The other 750 subjects did not receive treatment, *even though they were assigned to*. 
  
## Three groups of individuals 

With three groups of individuals, who should we compare to whom when estimating the treatment effect? 

1. **Group A**: 250 people who answered the doors? 
2. **Group B**: 750 people who didn't answer their doors? 
3. **Group C**: 1,000 people in the control group (on whose doors no one knocked)

---

# Introduction to Chapter 5 (cont'd) 

## *Field Experiments* considers three options: 

1. Compare group *A* to *C*: treatment individuals vs. control individuals 
2. Compare group *A* to groups *B* and *C* :treated individuals vs. untreated individuals 
3. Compare group *A* and *B* to group *C*: whol treatment group to whole control group

---

class: inverse, center, middle

# Example: Yahoo! Ad-Effectiveness 

---

# Yahoo! Ad Experiemnt 

## Group A 
- Assigned to treatment and received treatment 
- 64% of the treatment group 
- Purchased $1.81 per person 

## Group B 
- Assigned to treatment, *but did not receive* treatment 
- 36% of the treatment group 
- Purchased $2.04 per person 

## Group C 
- Assigned to control, *but did not receive* treatment 
- 100% of the control group
- Purchased $1.84 per person 

---

# Yahoo! Ad Experiemnt (cont'd) 

- The correct apples to apples comparison is \{*A* & *B*\} to *C*
- Treatment effect of $$\{(\$1.81 \times 0.64) + (\$2.04 \times 0.36) \} - \$1.84 = \mathbf{\$0.05}$$

## But, what is this effect? 

- Treatment effect is *diluted* but the 36% of consumers in the treatment group who did not receive ads and therefore could not have had any treatment effect
- This $0.04 estimate is called the **intent-to-treat (ITT)** treatment effect 
- The treatment effect on those who were *actually* treated must have been larger than $0.05
- Producing an unbiased estimate of the treatment effect on those actually treated requires *reweighing this ITT*. 

---

# Reading 

## Read *Field Experiments*, Section 5.1
- Section 5.1 introduces new notation about treatment since assignment to treatmetn no longer guarantees that a subject will (or did) receive treatment 
- As before, $d = 1$ indicates that someone received a dose of treatment, and $d = 0$ indicates that someone received a dose of control 
- Section 5.1 introduces new notation, $z$, that indicates whether someone was assigned ("azzigned" mnemonically) to treatment 

## Assignment and receiving treatment are distinct events 
- Someone might be assigned to treatment, $z=1$, but choose to take a dose of control, $d=0$
- In the future, we'll let subjects be assigned to control, $z=0$, but choose to take a dose of treatment, $d=1$

---

class: inverse, center, middle 

# Example: Blood Pressure

---

# Example: Blood Pressure

## Suppose our goal is to assess the effect of a new blood pressure medicine
  - 100 control individuals are giving nothing, $z=0$
  - 100 treatment individuals are provided with blood pressure medicine 
    - 60 individuals take their pills, $z=1, d=1$
    - 40 individuals do not take their pills, $z=1, d=0$

## Who are the compliers, and who are the never takers?     

---

# Example: Blood Pressure (cont'd) 

- 100 control group units did not take the pill, $z=0, d=0$, and have a **mean BP = 140**
- 60 compliers who took the pill, $z=1, d=1$, have a **mean BP = 150**. 
- 40 never-takers who did not take the pill, $z=1, d=0$, have a **mean BP of 100**

## Don't be tempted! 

- Tempting to naïvely conclude that pills increase blood pressure
  - People who take the pill have higher blood pressure than either of the groups that did not take the pill
- But, a more careful analysis would show that the ATE is, in fact, a *reduction* in blood pressure

---

# Reading: Skip *FE*, Section 5.2

## Key Takeaway #1 

- The **ITT** is the "intent-to-treat" effect 
  - The ITT is the difference of the average outcomes in the group assigned to receive treatment and the group assigned to receive control 
  - The $ITT = E[Y|Z=1] - E[Y|Z=0]$
  - This is a correct, *apples-to-apples* comparison 
  - But, this estimate will be diluted compared to the actual treatment effect for the people who received the treatment 
  - In other words, the ITT is the treatment effect of the *intention to treat*, $z$, on the outcome variable $Y$. 
  
---

# Reading: Skip *FE*, Section 5.2

## Key Takeaway #2

- The $ITT_{D}$ is the effect of being assigned to treatment, on *receiving a dose of treatment* 
- Because receiving a dose happens **after** random treatment assignment, it meets all the requirements of a causal effect
- $ITT_{D} = E[d_{i} | z_{i} = 1] - E[d_{i} | z_{i} = 0]$ 

## Blood Pressure Example 
- 60% of the treatment group received treatment, $E[d_{i} | z_{i} = 1] = 0.6$
- 0% of the control group received the treatment, $E[d_{i} |z_{i} = 0] = 0.0$. 
- And so, $ITT_{D} = E[d_{i} | z_{i} = 1] - E[d_{i} | z_{i} = 0] = 0.6 - 0.0 = \mathbf{0.6}$

## Alternative Terms 

- *Take up rate* 
- Or, alternative symbol, $\alpha$

---

# Reading: *FE*, Section 5.3

## Read *Field Experiments*, Section 5.3
- Gerber and Green draw an important distinction between the ATE and the CACE in this section 
  - The ATE is the average treatment effect for the whole population
  - The CACE is the average treatment effect for the population who comply with their assignment 
- When there is non-compliance, we cannot measure the potential outcomes to treatmetn for non-compliers -- none of them receive treatment! 
- Thus, when there is non-compliance, there is no guarantee that the ATE = CACE. 

---
